default:
  s3:
    bucket_name: "databrew.org"
    keys:
      household: "kwale/raw-form/reconbhousehold/reconbhousehold.csv"
      registration: "kwale/raw-form/reconaregistration/reconaregistration.csv"
