FROM rocker/verse:4.2.1
RUN apt-get update -y && apt-get install -y  make  pandoc  libicu-dev  libcurl4-openssl-dev  zlib1g-dev  git  libssl-dev  libgit2-dev  libxml2-dev  libgdal-dev  gdal-bin  libgeos-dev  libproj-dev  libsqlite3-dev  libpng-dev  libudunits2-dev  libfontconfig1-dev  libfreetype6-dev  imagemagick  libmagick++-dev  gsfonts && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
