name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      ## use docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ## checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create R deployment assets
        run: golem::add_dockerfile_with_renv(output_dir = "deploy")
        shell: Rscript {0}
      - name: Build Docker Base
        run: docker build -f deploy/Dockerfile_base --progress=plain -t reconmonitoring_base .
      - name: Build Docker file for recon
        run: docker build -f deploy/Dockerfile --progress=plain -t databrewllc/reconmonitoring:latest .
      - name: Push to Dockerhub
        run: docker push databrewllc/reconmonitoring:latest

