name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      ## use docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      ## checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker Base
        run: docker build -f Dockerfile_base --progress=plain -t reconmonitoring_base .
      - name: Build Docker file for recon
        run: docker build -f Dockerfile --progress=plain -t databrewllc/reconmonitoring:production .
      - name: Push to Dockerhub
        run: docker push databrewllc/reconmonitoring:production
      - name: Tag image based on commit SHA
        run: docker image tag databrewllc/reconmonitoring:production databrewllc/reconmonitoring:${GITHUB_SHA::7}
      - name: Push to Dockerhub with commit sha for version tracking
        run: docker push databrewllc/reconmonitoring:${GITHUB_SHA::7}
